// Code generated by tygo. DO NOT EDIT.
import type { Report } from './report.generated';

//////////
// source: backup.go

/**
 * BackupInfo 描述一份本地备份。
 */
export interface BackupInfo {
  /**
   * Name 是备份文件名，同时是下载时的标识。
   */
  name: string;
  /**
   * Reason 是备份原因：daily | manual | pre-upgrade。
   */
  reason: string;
  /**
   * CreatedAt 是备份时间（UTC，取自文件名）。
   */
  created_at: string;
  /**
   * Size 是文件大小，单位字节。
   */
  size: number /* int64 */;
}

//////////
// source: errors.go

/**
 * 字段错误码。
 */
export const FieldInvalid = "invalid";
/**
 * 字段错误码。
 */
export const FieldOutOfRange = "out_of_range";
/**
 * FieldRequired 表示必填字段缺失或为空。
 */
export const FieldRequired = "required";
/**
 * FieldPattern 表示值不匹配字段声明的 pattern。
 */
export const FieldPattern = "pattern_mismatch";
/**
 * FieldDuplicate 表示值与已有记录重复（如重名）。
 */
export const FieldDuplicate = "duplicate";
/**
 * FieldErrors 是校验失败时按字段给出的错误：键为点号路径
 * （如 retention.raw_hours、trusted_proxies[1]），值为 FieldInvalid、FieldOutOfRange、FieldRequired、FieldPattern 或 FieldDuplicate。
 */
export type FieldErrors = { [key: string]: string};

//////////
// source: history.go

/**
 * 历史数据的档位名称。
 */
export const HistoryTierRaw = "raw";
/**
 * 历史数据的档位名称。
 */
export const HistoryTier5Min = "5m";
/**
 * 历史数据的档位名称。
 */
export const HistoryTier1H = "1h";
/**
 * HistoryPoint 是历史曲线上的一个点。T 为时间（Unix 毫秒）：原始档是采样时刻，
 * 聚合档是桶起点；原始档的 Avg、Min、Max 三者相等。
 */
export interface HistoryPoint {
  t: number /* int64 */;
  avg: number /* float64 */;
  min: number /* float64 */;
  max: number /* float64 */;
}
/**
 * HistoryResult 是 GET /api/instances/:id/history 的响应。
 */
export interface HistoryResult {
  instance_id: string;
  item: string;
  /**
   * Field 是实际查询的字段（请求省略时为解析出的默认字段；该数据项没有历史时为空串）。
   */
  field: string;
  /**
   * Range 原样回显请求的时间范围。
   */
  range: string;
  /**
   * Tier 是按范围选中的档位：raw、5m、1h。
   */
  tier: string;
  /**
   * From、To 是查询的时间窗口（Unix 毫秒）。
   */
  from: number /* int64 */;
  to: number /* int64 */;
  points: HistoryPoint[];
}

//////////
// source: instance.go

/**
 * InstanceInput 是创建与更新实例的请求体。
 */
export interface InstanceInput {
  /**
   * PluginID 创建时必填；更新时可省略，出现且与原值不同视为非法（实例不能换插件）。
   */
  plugin_id?: string;
  name: string;
  /**
   * Config 是完整配置；密钥字段更新时缺省、为空串或回显的 {"set":true} 表示保留原值。
   */
  config: { [key: string]: any};
  /**
   * IntervalSeconds 是刷新间隔覆盖，0 表示沿用 manifest 的默认间隔。
   */
  interval_seconds: number /* int */;
}
/**
 * Instance 是实例列表项，也是详情与运行结果的公共部分。
 */
export interface Instance {
  id: string;
  plugin_id: string;
  name: string;
  /**
   * RunsOn 本期固定为 hub。
   */
  runs_on: string;
  /**
   * IntervalSeconds 是覆盖值（0 为未覆盖）；EffectiveIntervalSeconds 是实际生效的间隔。
   */
  interval_seconds: number /* int */;
  effective_interval_seconds: number /* int */;
  paused: boolean;
  /**
   * DisplayState 是统一展示状态（设计 3.5）；暂停的实例不做过期判定。
   */
  display_state: string;
  /**
   * Summary 与 ReportStatus 取自当前报告，从未成功采集时为空。
   */
  summary: string;
  report_status: string;
  report_stale: boolean;
  last_success_at?: string;
  /**
   * LastError 是最近一次失败的（已脱敏）文字，最近一次成功后为空。
   */
  last_error?: string;
  failures: number /* int */;
  /**
   * Issue 说明实例为何无法运行（插件消失、配置不完整、代理不可用等），可运行时为空。
   */
  issue?: string;
  created_at: string;
  updated_at: string;
}
/**
 * InstanceDetail 是单个实例的详情。
 */
export interface InstanceDetail {
  Instance: Instance;
  /**
   * Config 已脱敏：已设置的密钥显示为 {"set":true}。
   */
  config: { [key: string]: any};
  /**
   * Problems 是配置与当前插件 schema 不符的字段（按路径）。
   */
  problems?: FieldErrors;
  /**
   * Report 是当前报告，采集失败时为保留的旧值（已标记过期）；从未成功时为 null。
   */
  report?: Report;
}
/**
 * InstanceRunResult 是「保存并测试」的响应：同步运行一次的报告与运行后的实例状态。
 */
export interface InstanceRunResult {
  instance: Instance;
  report?: Report;
}
/**
 * ScreenRef 是引用某实例的 screen。
 */
export interface ScreenRef {
  id: string;
  name: string;
}
/**
 * InstanceDeleteResult 是删除实例的响应。screens 表在 M1d 才有，本期恒为空。
 */
export interface InstanceDeleteResult {
  affected_screens: ScreenRef[];
}

//////////
// source: plugin.go

/**
 * PluginInfo 是 GET /api/plugins 里一个插件的描述。面向用户的文本已按请求语言解析为单一字符串。
 */
export interface PluginInfo {
  id: string;
  version: string;
  name: string;
  /**
   * Kind 是 source | notifier。
   */
  kind: string;
  /**
   * Runtime 是 builtin | exec。
   */
  runtime: string;
  /**
   * Origin 是插件来源：builtin（编译期注册）| exec（插件目录）。
   */
  origin: string;
  /**
   * RunsOn 是允许的运行位置：hub、agent。
   */
  runs_on: string[];
  /**
   * IntervalSeconds 是插件默认刷新间隔（未写 interval 时为默认值 300）。
   */
  interval_seconds: number /* int */;
  /**
   * MinIntervalSeconds 是实例刷新间隔的下限，0 表示插件未声明（只受全局 5 秒下限约束）。
   */
  min_interval_seconds: number /* int */;
  timeout_seconds: number /* int */;
  config_schema: PluginField[];
  outputs: PluginOutput[];
  widgets: PluginWidget[];
}
/**
 * PluginField 是 config_schema 的一个字段，前端据此生成配置表单。
 */
export interface PluginField {
  key: string;
  type: string;
  title: string;
  help?: string;
  /**
   * Required 表示必填。
   */
  required: boolean;
  default?: any;
  min?: number /* float64 */;
  max?: number /* float64 */;
  pattern?: string;
  /**
   * VisibleWhen 中的条件全部成立才显示该字段。
   */
  visible_when?: PluginCondition[];
  /**
   * Options 仅 enum 字段有。
   */
  options?: PluginOption[];
  allow_query?: boolean;
  allow_public_http?: boolean;
  follow_redirects?: boolean;
  /**
   * SecretValues 仅 kv 字段：值是密钥。
   */
  secret_values?: boolean;
  /**
   * Fields 仅 object_list 字段：每个元素的子字段。
   */
  fields?: PluginField[];
}
/**
 * PluginCondition 是 visible_when 的一项：字段 Key 的值等于 Values 中任意一个。
 */
export interface PluginCondition {
  key: string;
  values: any[];
}
/**
 * PluginOption 是 enum 字段的一个选项。
 */
export interface PluginOption {
  value: string;
  title: string;
}
/**
 * PluginOutput 是插件产出的一个数据项声明；Key 以 [*] 结尾表示动态集合。
 */
export interface PluginOutput {
  key: string;
  type: string;
  title: string;
}
/**
 * PluginWidget 是插件声明的小组件。
 */
export interface PluginWidget {
  id: string;
  name: string;
  sizes: PluginWidgetSize[];
}
/**
 * PluginWidgetSize 是小组件的一种尺寸及其模板与数据绑定。
 */
export interface PluginWidgetSize {
  /**
   * Size 是原文，如 2x1。
   */
  size: string;
  cols: number /* int */;
  rows: number /* int */;
  template: string;
  bind: PluginBinding[];
}
/**
 * PluginBinding 是小组件的一个绑定槽。
 */
export interface PluginBinding {
  slot: string;
  /**
   * List 为 true 表示该槽按列表写法声明，可绑定多个数据项。
   */
  list: boolean;
  refs: PluginItemRef[];
}
/**
 * PluginItemRef 是对数据项字段的引用；Field 为空表示取该类型的默认字段。
 */
export interface PluginItemRef {
  item: string;
  field?: string;
}
/**
 * PluginProblem 是 manifest 里的一个具体问题。
 */
export interface PluginProblem {
  /**
   * Line 是 plugin.yaml 行号，0 表示未知。
   */
  line: number /* int */;
  path?: string;
  message: string;
}
/**
 * PluginLoadIssue 是某个插件目录未能加载的原因（或与内置插件冲突）。
 */
export interface PluginLoadIssue {
  /**
   * Dir 是插件目录名。
   */
  dir: string;
  id: string;
  /**
   * Kind 是 invalid_manifest | id_mismatch | runtime_not_exec | missing_run |
   * not_executable | insecure | conflict。
   */
  kind: string;
  message: string;
  problems?: PluginProblem[];
}
/**
 * PluginList 是 GET /api/plugins 与 POST /api/plugins/rescan 的响应。
 */
export interface PluginList {
  plugins: PluginInfo[];
  /**
   * Errors 是加载失败的目录；Conflicts 是与内置插件 id 冲突的目录（供系统页提示）。
   */
  errors: PluginLoadIssue[];
  conflicts: PluginLoadIssue[];
  /**
   * PluginDir 是 exec 插件目录的绝对路径，供管理界面提示用户把插件放到哪里。
   */
  plugin_dir: string;
}
/**
 * PluginLookupRequest 是 POST /api/plugins/{id}/lookup/{key} 的请求体。
 */
export interface PluginLookupRequest {
  query: string;
}
/**
 * PluginCandidate 是 lookup 字段的一个候选项。
 */
export interface PluginCandidate {
  value: string;
  label: string;
}
/**
 * PluginLookupResponse 是 lookup 的响应。
 */
export interface PluginLookupResponse {
  candidates: PluginCandidate[];
}

//////////
// source: proxy.go

/**
 * ProxyLocationHub 表示仅中枢所在网络可用。
 */
export const ProxyLocationHub = "hub";
/**
 * ProxyLocationLAN 表示仅局域网内的 agent 可用。
 */
export const ProxyLocationLAN = "lan";
/**
 * ProxyLocationAny 表示任意位置可用。
 */
export const ProxyLocationAny = "any";
/**
 * 代理协议取值。
 */
export const ProxySchemeHTTP = "http";
/**
 * 代理协议取值。
 */
export const ProxySchemeHTTPS = "https";
/**
 * 代理协议取值。
 */
export const ProxySchemeSOCKS5 = "socks5";
/**
 * 代理协议取值。
 */
export const ProxySchemeSOCKS5H = "socks5h";
/**
 * Proxy 是全局代理列表中的一项（GET 响应）。认证永不回显，只给出是否已设置。
 */
export interface Proxy {
  id: string;
  name: string;
  /**
   * Scheme 是 http | https | socks5 | socks5h。
   */
  scheme: string;
  /**
   * Address 是 host:port。
   */
  address: string;
  /**
   * RemoteDNS 表示域名由代理端解析：socks5h 恒为 true，http/https 代理天然如此也为 true，
   * 仅 socks5（本地解析）为 false。
   */
  remote_dns: boolean;
  /**
   * Location 是可用位置：hub | lan | any。
   */
  location: string;
  /**
   * Auth 只表示是否设置了认证。
   */
  auth: ProxyAuthState;
  created_at: string;
  updated_at: string;
}
/**
 * ProxyAuthState 是认证的回显形式：{"set": true}。
 */
export interface ProxyAuthState {
  set: boolean;
}
/**
 * ProxyAuthInput 是提交的代理认证。
 */
export interface ProxyAuthInput {
  username: string;
  password: string;
}
/**
 * ProxyInput 是创建与更新代理的请求体。
 */
export interface ProxyInput {
  name: string;
  scheme: string;
  address: string;
  /**
   * RemoteDNS 对 socks5 有意义：为 true 时等同于 socks5h。其余协议忽略。
   */
  remote_dns: boolean;
  /**
   * Location 缺省为 any。
   */
  location: string;
  /**
   * Auth 缺省（或用户名密码均为空）表示保留原值；新建时表示无认证。
   */
  auth?: ProxyAuthInput;
  /**
   * ClearAuth 为 true 时清除已保存的认证（不得与非空 Auth 同时提交）。
   */
  clear_auth?: boolean;
}
/**
 * ProxyReferrer 是引用某个代理的监控实例。
 */
export interface ProxyReferrer {
  id: string;
  name: string;
}
/**
 * ProxyTestRequest 是代理测试请求体；URL 缺省为 https://www.google.com/generate_204。
 */
export interface ProxyTestRequest {
  url?: string;
}
/**
 * ProxyTestResult 是代理测试结果。请求失败不是 HTTP 错误，而是 OK=false 并给出 Error。
 */
export interface ProxyTestResult {
  ok: boolean;
  /**
   * URL 是实际请求的目标地址。
   */
  url: string;
  /**
   * LatencyMS 是从发起到收到响应头的耗时，毫秒；失败时为 0。
   */
  latency_ms: number /* int64 */;
  /**
   * Status 是目标返回的 HTTP 状态码；失败时为 0。
   */
  status: number /* int */;
  /**
   * Error 是失败原因，成功时为空。
   */
  error?: string;
}

//////////
// source: settings.go
/*
Package model 定义前后端共享的数据模型（前端 TS 类型由此生成）。
*/

/**
 * Settings 是全局设置，整份存为一行 JSON。
 */
export interface Settings {
  /**
   * Language 界面语言：zh 或 en。
   */
  language: string;
  /**
   * Timezone IANA 时区名，如 Asia/Shanghai。
   */
  timezone: string;
  /**
   * AccessURL 对外访问地址；为空表示未配置。
   */
  access_url: string;
  /**
   * TrustedProxies 受信任反代，单个 IP 或 CIDR；序列化时始终为数组。
   */
  trusted_proxies: string[];
  /**
   * HTTPSEnabled 是否启用 HTTPS；修改后需重启才生效。
   */
  https_enabled: boolean;
  /**
   * ReduceEffects 降低屏幕特效。
   */
  reduce_effects: boolean;
  retention: RetentionSettings;
  backup: BackupSettings;
}
/**
 * RetentionSettings 历史数据保留期。
 */
export interface RetentionSettings {
  /**
   * RawHours 原始采样保留小时数（1–168）。
   */
  raw_hours: number /* int */;
  /**
   * FiveMinDays 5 分钟聚合保留天数（1–365）。
   */
  five_min_days: number /* int */;
  /**
   * HourDays 1 小时聚合保留天数（1–1825）。
   */
  hour_days: number /* int */;
}
/**
 * BackupSettings 每日备份设置。
 */
export interface BackupSettings {
  /**
   * DailyAt 每日备份时刻，HH:MM。
   */
  daily_at: string;
  /**
   * Keep 保留份数（1–30）。
   */
  keep: number /* int */;
}
