// Code generated by tygo. DO NOT EDIT.
import type {
  Instance,
  LayoutState,
  ResolvedLayout,
  ScreenDisplaySettings,
  ScreenInstanceData,
  ScreenState,
  Settings,
  Viewport,
} from './model.generated';

//////////
// source: message.go

/** ServerMessageType 是服务端 → 客户端消息的 type 取值。 */
export type ServerMessageType = "snapshot" | "patch" | "pong" | "error" | "screen_control";
/** ClientMessageType 是客户端 → 服务端消息的 type 取值。 */
export type ClientMessageType = "subscribe" | "ping" | "viewport_report";
/**
 * 服务端 → 客户端的消息类型。
 */
export const TypeSnapshot: ServerMessageType = "snapshot";
/**
 * 服务端 → 客户端的消息类型。
 */
export const TypePatch: ServerMessageType = "patch";
/**
 * 服务端 → 客户端的消息类型。
 */
export const TypePong: ServerMessageType = "pong";
/**
 * 服务端 → 客户端的消息类型。
 */
export const TypeError: ServerMessageType = "error";
/**
 * TypeScreenControl 是一次性屏幕指令（refresh、switch），只发给屏幕会话，立即入队。
 */
export const TypeScreenControl: ServerMessageType = "screen_control";
/**
 * 客户端 → 服务端的消息类型。
 */
export const TypeSubscribe: ClientMessageType = "subscribe";
/**
 * 客户端 → 服务端的消息类型。
 */
export const TypePing: ClientMessageType = "ping";
/**
 * TypeViewportReport 是屏幕端的状态上报（viewport、触摸能力、当前 screen），仅屏幕会话有效。
 */
export const TypeViewportReport: ClientMessageType = "viewport_report";
/**
 * 会话角色。
 */
export const RoleAdmin = "admin";
/**
 * 会话角色。
 */
export const RoleScreen = "screen";
/**
 * TopicInstances 全部实例状态（仅管理员会话可订阅）。
 */
export const TopicInstances = "instances";
/**
 * TopicSettings 全局设置：管理员得到完整设置，屏幕会话只得到屏幕需要的部分。
 */
export const TopicSettings = "settings";
/**
 * TopicLayout 屏幕布局：管理员得到原始布局与版本，屏幕会话得到解析后的布局。
 */
export const TopicLayout = "layout";
/**
 * TopicScreenState 屏幕当前状态（亮灭、主题、下一次变化）：两种角色同形。
 */
export const TopicScreenState = "screen_state";
/**
 * TopicScreenData 当前布局引用的实例的展示状态与最新数据项：屏幕会话默认订阅，管理员可订阅做预览。
 */
export const TopicScreenData = "screen_data";
/**
 * EntityInstanceState 载荷为该实例的完整 Instance（与 GET /api/instances 列表项同形），前端按 id 覆盖。
 */
export const EntityInstanceState = "instance_state";
/**
 * EntityInstanceRemoved 只带 id。
 */
export const EntityInstanceRemoved = "instance_removed";
/**
 * EntitySettings 管理员会话的载荷为完整设置，屏幕会话的载荷为 ScreenSettings。
 */
export const EntitySettings = "settings";
/**
 * EntityLayout 管理员会话的载荷为 Layout（原始布局与版本），屏幕会话的载荷为 ResolvedLayout。
 */
export const EntityLayout = "layout";
/**
 * EntityScreenState 载荷为 ScreenState。
 */
export const EntityScreenState = "screen_state";
/**
 * EntityScreenData 载荷为发生变化的实例的 ScreenData，客户端按 instance_id 合并覆盖。
 */
export const EntityScreenData = "screen_data";
/**
 * ErrSubscribeDenied 当前会话无权订阅所请求的主题，details.topics 列出被拒的主题。
 */
export const ErrSubscribeDenied = "ws.subscribe_denied";
/**
 * ErrBadMessage 消息不是合法 JSON，或 type 未知。
 */
export const ErrBadMessage = "ws.bad_message";
/**
 * ScreenSettings 是屏幕会话能看到的设置子集。
 */
export interface ScreenSettings {
  language: string;
  timezone: string;
  reduce_effects: boolean;
  screen: ScreenDisplaySettings;
}
/**
 * Snapshot 是连接建立后（以及每次 subscribe 之后）下发的全量状态。
 */
export interface Snapshot {
  type: ServerMessageType;
  /**
   * Build 是中枢的构建版本，与 index.html 注入的 pimon-build 同源；前端据此发现中枢升级。
   */
  build: string;
  /**
   * ServerTime 是服务端当前时间，前端据此校正时钟偏差。
   */
  server_time: string;
  /**
   * Role 是当前会话角色：admin 或 screen。
   */
  role: string;
  /**
   * Topics 是当前生效的订阅主题。
   */
  topics: string[];
  /**
   * Settings 仅管理员会话有值。
   */
  settings?: Settings;
  /**
   * ScreenSettings 仅屏幕会话有值。
   */
  screen_settings?: ScreenSettings;
  /**
   * Instances 是订阅范围内的全部实例；未订阅 instances 时为空数组。
   */
  instances: Instance[];
  /**
   * Layout 是原始布局与版本，仅管理员会话且订阅了 layout 时有值。
   */
  layout?: LayoutState;
  /**
   * ResolvedLayout 是解析后的布局，仅屏幕会话且订阅了 layout 时有值。
   */
  resolved_layout?: ResolvedLayout;
  /**
   * ScreenState 是屏幕当前状态，订阅了 screen_state 时有值。
   */
  screen_state?: ScreenState;
  /**
   * ScreenData 是当前布局引用的实例数据，订阅了 screen_data 时有值（没有引用时为空数组）。
   */
  screen_data?: ScreenInstanceData[];
}
/**
 * Patch 是按实体的增量更新。Entity 决定哪些字段有值。
 */
export interface Patch {
  type: ServerMessageType;
  server_time: string;
  entity: string;
  /**
   * ID 是被删除的实例 id（instance_removed）。
   */
  id?: string;
  instance?: Instance;
  settings?: Settings;
  screen_settings?: ScreenSettings;
  /**
   * Layout 仅 layout 实体、管理员会话有值；ResolvedLayout 仅 layout 实体、屏幕会话有值。
   */
  layout?: LayoutState;
  resolved_layout?: ResolvedLayout;
  /**
   * ScreenState 仅 screen_state 实体有值。
   */
  screen_state?: ScreenState;
  /**
   * ScreenData 仅 screen_data 实体有值：本次发生变化的实例，客户端按 instance_id 覆盖。
   */
  screen_data?: ScreenInstanceData[];
}
/**
 * ScreenControl 是发给屏幕会话的一次性指令：refresh 让屏幕重新加载，switch 让屏幕切到 screen_id。
 */
export interface ScreenControl {
  type: ServerMessageType;
  server_time: string;
  action: string;
  /**
   * ScreenID 仅 switch 有值。
   */
  screen_id?: string;
  /**
   * OpID 是对应的操作记录 id。
   */
  op_id: number /* int64 */;
}
/**
 * Pong 是对 ping 的应答，带服务端时间供前端校正时钟。
 */
export interface Pong {
  type: ServerMessageType;
  server_time: string;
}
/**
 * ErrorBody 是协议级错误的内容，形状与 REST 错误体一致。
 */
export interface ErrorBody {
  code: string;
  details: { [key: string]: any};
}
/**
 * ErrorMessage 是协议级错误消息；收到它后连接仍然可用。
 */
export interface ErrorMessage {
  type: ServerMessageType;
  error: ErrorBody;
}
/**
 * ClientMessage 是客户端发来的消息，按 Type 取用对应字段。
 */
export interface ClientMessage {
  type: ClientMessageType;
  /**
   * Topics 用于 subscribe：声明完整的订阅主题集合，服务端随后重发 snapshot。
   */
  topics?: string[];
  /**
   * 以下三项用于 viewport_report，仅屏幕会话有效（管理员会话发来的被忽略）：
   * Viewport 是当前视口（CSS 像素），CoarsePointer 是是否有触摸（粗指针）能力，CurrentScreen 是正在显示的 screen id。
   * 三者都可缺省，缺省的不更新。
   */
  viewport?: Viewport;
  coarse_pointer?: boolean;
  current_screen?: string;
}
