// Code generated by tygo. DO NOT EDIT.

//////////
// source: display.go

/**
 * DisplayState 是实例/小组件的统一展示状态（设计 3.5）。
 */
export type DisplayState = string;
/**
 * 展示状态，共 10 个取值；前六个是覆盖 report.status 的状态，后四个对应 report.status。
 */
export const DisplayUnconfigured: DisplayState = "unconfigured"; // 占位，尚未绑定实例
/**
 * 展示状态，共 10 个取值；前六个是覆盖 report.status 的状态，后四个对应 report.status。
 */
export const DisplayBroken: DisplayState = "broken"; // 引用失效
/**
 * 展示状态，共 10 个取值；前六个是覆盖 report.status 的状态，后四个对应 report.status。
 */
export const DisplayOffline: DisplayState = "offline"; // 设备离线
/**
 * 展示状态，共 10 个取值；前六个是覆盖 report.status 的状态，后四个对应 report.status。
 */
export const DisplayMaintenance: DisplayState = "maintenance"; // 维护中
/**
 * 展示状态，共 10 个取值；前六个是覆盖 report.status 的状态，后四个对应 report.status。
 */
export const DisplayError: DisplayState = "error"; // 采集失败：采集没做成
/**
 * 展示状态，共 10 个取值；前六个是覆盖 report.status 的状态，后四个对应 report.status。
 */
export const DisplayStale: DisplayState = "stale"; // 过期
/**
 * 展示状态，共 10 个取值；前六个是覆盖 report.status 的状态，后四个对应 report.status。
 */
export const DisplayOK: DisplayState = "ok";
/**
 * 展示状态，共 10 个取值；前六个是覆盖 report.status 的状态，后四个对应 report.status。
 */
export const DisplayWarning: DisplayState = "warning";
/**
 * 展示状态，共 10 个取值；前六个是覆盖 report.status 的状态，后四个对应 report.status。
 */
export const DisplayCritical: DisplayState = "critical";
/**
 * 展示状态，共 10 个取值；前六个是覆盖 report.status 的状态，后四个对应 report.status。
 */
export const DisplayUnknown: DisplayState = "unknown"; // 插件判断不出，与 error 不同
/**
 * StaleFactor 是过期判定的间隔倍数：超过刷新间隔的 3 倍仍未成功才算过期。
 */
export const StaleFactor = 3;
/**
 * DisplayInput 是计算展示状态所需的事实，由调用方（实例仓库、屏幕、agent）收集。
 */
export interface DisplayInput {
  Unconfigured: boolean; // 占位，尚未绑定实例
  Broken: boolean; // 引用失效（实例已删、设备已吊销、插件消失或尺寸不再支持）
  Offline: boolean; // 设备离线（M1 不会出现）
  Maintenance: boolean; // 设备维护模式（M1 不会出现）
  LastFailed: boolean; // 最近一次采集失败
  /**
   * LastSuccessAt 是最后一次成功采集（Streamer 为最后一次 emit）的 Unix 毫秒；0 表示从未成功。
   */
  LastSuccessAt: number /* int64 */;
  /**
   * Interval 是刷新间隔；StaleAfter > 0 时（Streamer 按 manifest 声明）以它为过期阈值，忽略 Interval。
   */
  Interval: any /* time.Duration */;
  StaleAfter: any /* time.Duration */;
  /**
   * ReportStatus 是最近一份成功报告的 status；空或非法按 unknown 处理。
   */
  ReportStatus: Status;
}

//////////
// source: key.go

/**
 * Key 是数据项键名的解析结果。固定键如 quota.5h；动态集合成员如 disk[/vol1]、
 * container[nginx]；disk[*] 是规则中使用的通配（只出现在引用里，不会是报告中的 key）。
 */
export interface Key {
  Prefix: string; // 固定键的全名，或动态集合的前缀（disk）
  Member: string; // 动态成员（/vol1）；通配时为 "*"
  Dynamic: boolean;
  Wildcard: boolean;
}
/**
 * Ref 是结构化字段引用；Field 为空表示取默认字段。
 */
export interface Ref {
  Item: string;
  Field: string;
}

//////////
// source: parse.go

/**
 * ValidationError 汇总报告的全部校验问题，每条以字段路径开头（如 items[0].key）。
 */
export interface ValidationError {
  Problems: string[];
}

//////////
// source: types.go

/**
 * Status 是插件对被测对象的判断；采集本身失败不用它表达。
 */
export type Status = string;
/**
 * 报告状态。
 */
export const StatusOK: Status = "ok";
/**
 * 报告状态。
 */
export const StatusWarning: Status = "warning";
/**
 * 报告状态。
 */
export const StatusCritical: Status = "critical";
/**
 * 报告状态。
 */
export const StatusUnknown: Status = "unknown";
/**
 * 数据项类型。
 */
export const TypeGauge = "gauge";
/**
 * 数据项类型。
 */
export const TypeNumber = "number";
/**
 * 数据项类型。
 */
export const TypeQuota = "quota";
/**
 * 数据项类型。
 */
export const TypeMoney = "money";
/**
 * 数据项类型。
 */
export const TypeState = "state";
/**
 * 数据项类型。
 */
export const TypeText = "text";
/**
 * 数据项类型。
 */
export const TypeTable = "table";
/**
 * Item 是报告中的一个数据项。各类型只使用自己的字段（见 FieldsOf），
 * 数值字段用指针区分“缺失”与 0。
 */
export interface Item {
  key: string;
  type: string;
  value?: number /* float64 */;
  unit?: string;
  min?: number /* float64 */;
  max?: number /* float64 */;
  used?: number /* float64 */;
  total?: number /* float64 */;
  remaining?: number /* float64 */;
  remaining_pct?: number /* float64 */;
  resets_at?: number /* int64 */;
  expires_at?: number /* int64 */;
  label?: string;
  amount?: number /* float64 */;
  currency?: string;
  state?: Status;
  text?: string;
  columns?: string[];
  rows?: any[][];
  /**
   * Error 是条目级错误（如“mdadm 调用失败”），由条目级状态表达，数据项仍保留。
   */
  error?: string;
  /**
   * Stale 由运行时在采集失败保留旧值时置位，插件自报的值会被解析忽略。
   */
  stale?: boolean;
}
/**
 * Report 是插件一次采集的全量快照，同时是 exec 插件 stdout 的 JSON 结构。
 */
export interface Report {
  status: Status;
  summary?: string;
  collected_at?: number /* int64 */;
  duration_ms?: number /* int64 */;
  items?: Item[];
  events?: Event[];
  /**
   * State 是插件私有状态，对运行时不透明，下次运行时传回。
   */
  state?: string;
  /**
   * Stale 表示本报告是采集失败后保留的旧值。
   */
  stale?: boolean;
}
/**
 * Event 是报告中的事件。本期只校验通用字段 id、type、at，不解释 type；
 * 其余字段（seq 等）原样保存在 Extra 中。
 */
export interface Event {
  ID: string;
  Type: string;
  At: number /* int64 */;
  Extra: { [key: string]: any /* json.RawMessage */};
}
